{"version":3,"sources":["../../../lib/test/errors.js"],"names":["module","exports","TestError","Error","constructor","field","expected","received","resp","body","JSON","stringify","Object","assign"],"mappings":"AAAA;;AAEAA,MAAM,CAACC,OAAP,CAAeC,SAAf,GAA2B,MAAMA,SAAN,SAAwBC,KAAxB,CAA8B;AACvDC,EAAAA,WAAW,CAACC,KAAD,EAAQC,QAAR,EAAkBC,QAAlB,EAA4BC,IAA5B,EAAkCC,IAAlC,EAAwC;AACjD,UACG,0BAAyBC,IAAI,CAACC,SAAL,CAAeL,QAAf,CAAyB,eAAcI,IAAI,CAACC,SAAL,CAAeJ,QAAf,CAAyB,EAD5F;AAGAK,IAAAA,MAAM,CAACC,MAAP,CAAc,IAAd,EAAoB;AAAER,MAAAA,KAAF;AAASC,MAAAA,QAAT;AAAmBC,MAAAA,QAAnB;AAA6BC,MAAAA,IAA7B;AAAmCC,MAAAA;AAAnC,KAApB;AACD;;AANsD,CAAzD","sourcesContent":["'use strict';\n\nmodule.exports.TestError = class TestError extends Error {\n  constructor(field, expected, received, resp, body) {\n    super(\n      `Test failed, expected: ${JSON.stringify(expected)}, received: ${JSON.stringify(received)}`\n    );\n    Object.assign(this, { field, expected, received, resp, body });\n  }\n};\n"],"file":"errors.js"}